# Makefile per compilare il progetto 

CC       = gcc
CFLAGS   = -Wall -Wextra -std=gnu11 -O2
LDFLAGS  =

TARGETS  = server client

.PHONY: all clean

all: $(TARGETS)

server: server.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

client: client.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

clean:
	rm -f $(TARGETS)
